# Exported from Render on 2025-12-05T04:36:30Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Letuxlauda_mini_appi
      runtime: python
      repo: https://github.com/letuxlauda-lgtm/Letuxlauda_mini_appi
      plan: free
      region: virginia
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
      autoDeployTrigger: commit
